Repository algolia/algoliasearch-magento-2, pull requests merged in 2019-10, with the labels that each got.

#869 Bump to version 1.12.0
  CHANGELOG.md
  README.md
  composer.json
  etc/module.xml
Labels: Do not merge, WIP

#813 Fix warning on count() in AdditionalSectionHelper
  Helper/Entity/AdditionalSectionHelper.php
Labels: WIP

#878 Fix errors in code instead ignore in PHPStan
  Block/Navigation/Renderer/CategoryRenderer.php
  Block/Navigation/Renderer/DefaultRenderer.php
  Block/Navigation/Renderer/SliderRenderer.php
  Controller/Adminhtml/Landingpage/Duplicate.php
  Controller/Adminhtml/Query/Save.php
  Controller/Adminhtml/Queue/AbstractAction.php
  Model/Layer/Filter/Decimal.php
  Model/Layer/Filter/Price.php
  Plugin/BackendFilterRendererPlugin.php
  etc/di.xml
  phpstan.neon
Labels: Enhancement
