Repository algolia/algoliasearch-magento-2, pull requests merged in 2020-06, with the labels that each got.

#1028 Backport CircleCI changes
  .circleci/config.yml
Labels: v1.x

#1031 Prevent division by zero in the Notice Helper
  Helper/ConfigHelper.php
Labels: v1.x

#1029 Fix query rules empty array by using copyRules method
  Helper/AlgoliaHelper.php
Labels: v2.x

#1030 Fix query rules empty array by using scopedCopyIndex method
  Helper/AlgoliaHelper.php
Labels: v1.x

#1027 Removed obsolete trigger for catalog_product_entity_media_gallery
  etc/mview.xml
Labels: v2.x

#1013 Remove extra grid.css import
  view/frontend/web/internals/autocomplete.css
Labels: v2.x

#1039 Added CSP whitelisted hosts for Magento 2.3.5 or higher
  etc/csp_whitelist.xml
Labels: v2.x

#1034 Refactor getSalesData() method for optimisation
  Helper/Data.php
Labels: v2.x

#1038 Fix ProductHelper for bundle subproducts error
  Helper/Entity/ProductHelper.php
Labels: v2.x

#1041 Backport - Refactor getSalesData() method for optimisation
  Helper/Data.php
Labels: v1.x

#1042 Switch from priceRanges to input ranges widget for ISV4
  Model/Source/Facets.php
  view/frontend/web/instantsearch.js
Labels: v2.x

#1043 Activate "filterPromotes" attribute for created Merchandising Rules (…
  Helper/MerchandisingHelper.php
Labels: v2.x

#1045 Activate "filterPromotes" attribute for created Merchandising Rules
  Helper/MerchandisingHelper.php
Labels: v1.x

#969 Add category_without_path only if categories is searchable
  Helper/Entity/ProductHelper.php
Labels: Needs backport, v2.x

#1016 Queue doesn't update products unless enabled globally
  Model/IndexMover.php
Labels: Needs backport, v2.x

#1049 Update readme and contribution
  .github/CONTRIBUTING.md
  README.md
Labels: v2.x

#1050 Update readme and contribution
  .github/CONTRIBUTING.md
  README.md
Labels: v1.x

#1051 Backport to 1.x Community PRs
  Helper/Entity/ProductHelper.php
  Model/IndexMover.php
Labels: v1.x

#1052 Backport CircleCI changes
  .circleci/config.yml
Labels: v1.x

#1047 Bump to version 1.13.2
  CHANGELOG.md
  README.md
  composer.json
  etc/module.xml
Labels: v1.x

#1054 Release 1.13.2
  .circleci/config.yml
  .github/CONTRIBUTING.md
  CHANGELOG.md
  Helper/AlgoliaHelper.php
  Helper/ConfigHelper.php
  Helper/Data.php
  Helper/Entity/ProductHelper.php
  Helper/MerchandisingHelper.php
  Model/IndexMover.php
  README.md
  composer.json
  etc/csp_whitelist.xml
  etc/module.xml
  etc/mview.xml
Labels: v1.x

#1056 Release 2.0.1
  .circleci/config.yml
  .github/CONTRIBUTING.md
  CHANGELOG.md
  Helper/AlgoliaHelper.php
  Helper/ConfigHelper.php
  Helper/Data.php
  Helper/Entity/ProductHelper.php
  Helper/MerchandisingHelper.php
  Model/IndexMover.php
  Model/Source/Facets.php
  README.md
  composer.json
  etc/csp_whitelist.xml
  etc/module.xml
  etc/mview.xml
  view/frontend/web/instantsearch.js
  view/frontend/web/internals/autocomplete.css
Labels: v2.x
