Repository algolia/algoliasearch-magento-2, pull requests merged in 2020-07, with the labels that each got.

#1058 Update setUserToken to cap character length
  Helper/InsightsHelper.php
Labels: v2.x

#1060 Set forwardToReplicas for copy rules to false
  Helper/AlgoliaHelper.php
Labels: v1.x

#1059 Set forwardToReplicas for copy rules to false
  Helper/AlgoliaHelper.php
Labels: v2.x

#1061 Restore "search as you type" feature for v2
  view/frontend/web/instantsearch.js
  view/frontend/web/internals/autocomplete.css
Labels: v2.x

#1012 Fix error on URL during Pages indexing
  Helper/Entity/PageHelper.php
Labels: Question, v2.x

#1015 make sure original price range is saved for configurables
  Helper/Entity/Product/PriceManager/Bundle.php
  Helper/Entity/Product/PriceManager/ProductWithChildren.php
Labels: Question
