Repository algolia/algoliasearch-magento-2, pull requests merged in 2020-09, with the labels that each got.

#1068 remove less than IE9 condition from configuration template
  view/frontend/templates/internals/configuration.phtml
Labels: v2.x

#1069 Instantsearch Category Filter when category facet is not configured
  view/frontend/web/instantsearch.js
Labels: v2.x

#1070 Add messaging for indexing queue and logs
  view/adminhtml/layout/algolia_algoliasearch_queue_log.xml
  view/adminhtml/templates/queue/log/helper.phtml
  view/adminhtml/templates/queue/status.phtml
  view/adminhtml/web/css/common.css
Labels: Needs backport, v2.x

#1071 Remove IdentityInterface from Indexing Queue Job model class
  Model/Job.php
Labels: Needs backport, v2.x

#1040 Added algolia/algoliasearch-inventory-magento-2 to suggested modules
  composer.json
Labels: v1.x

#1072 Update for multi-condition rules
  Helper/Entity/ProductHelper.php
  Helper/MerchandisingHelper.php
Labels: Needs backport, v2.x

#1079 Fix serialization issue with 2.4
  Model/Source/AbstractTable.php
  etc/config.xml
Labels: v2.x

#1082 Update subproduct adaptive images on color
  Helper/Entity/ProductHelper.php
Labels: v2.x

#1083 Exclude category facet from clearRefinement on category pages
  view/frontend/web/instantsearch.js
Labels: v2.x

#1076 Set ACL resource titles are translatable.
  etc/acl.xml
Labels: v1.x

#1081 Update Personalisation Order Conversion
  Model/Observer/Insights/CheckoutOnepageControllerSuccessAction.php
Labels: v2.x

#1084 Update bundle with updated IS and autocomplete versions
  view/frontend/web/internals/algoliaBundle.min.js
  view/frontend/web/internals/algoliaBundle.min.js.map
Labels: v2.x

#1087 1.x Backport - Update for multi-condition rules
  Helper/Entity/ProductHelper.php
  Helper/MerchandisingHelper.php
Labels: v1.x

#1088 1.x Backport - Remove IdentityInterface from Indexing Queue Job model class
  Model/Job.php
Labels: v1.x

#1091 2.x Backport - Bundle and javascript optimisations
  Model/Observer/Insights/CheckoutOnepageControllerSuccessAction.php
  view/frontend/web/instantsearch.js
  view/frontend/web/internals/algoliaBundle.min.js
  view/frontend/web/internals/algoliaBundle.min.js.map
Labels: v2.x
