Repository algolia/algoliasearch-magento-2, pull requests merged in 2022-04, with the labels that each got.

#1174 Added release.yml for automating release notes.
  .github/release.yml
Labels: Enhancement

#1173 Algolia Search Composer update for magento 2.4.4 dependencies
  .circleci/config.yml
  .php-cs-fixer.php
  Block/Adminhtml/Job/View.php
  Block/Adminhtml/Queue/Status.php
  Block/Navigation/Renderer/CategoryRenderer.php
  Block/Navigation/Renderer/DefaultRenderer.php
  Block/Navigation/Renderer/PriceRenderer.php
  Block/Navigation/Renderer/SliderRenderer.php
  Controller/Adminhtml/Reindex/Save.php
  Helper/Adapter/FiltersHelper.php
  Helper/AlgoliaHelper.php
  Helper/AnalyticsHelper.php
  Helper/Configuration/NoticeHelper.php
  Helper/Data.php
  Helper/Entity/CategoryHelper.php
  Helper/Entity/Product/PriceManager/ProductWithoutChildren.php
  Helper/MerchandisingHelper.php
  Model/ExtensionNotification.php
  Model/ImageUploader.php
  Model/Indexer/Category.php
  Model/Job.php
  Model/LandingPage.php
  Model/Observer/Merchandising.php
  Model/Query.php
  Model/Queue.php
  Test/Integration/ConfigTest.php
  Test/Integration/PagesIndexingTest.php
  ViewModel/Adminhtml/Analytics/Overview.php
  composer.json
Labels: Enhancement, Feature

#1172 Requirejs not definded on swagger page fix
  Model/Observer.php
Labels: Bug
