Repository algolia/algoliasearch-magento-2, pull requests merged in 2022-05, with the labels that each got.

#1178 MAGE-207 userToken not properly being sent with M2
  view/frontend/web/insights.js
Labels: Bug

#1179 Updated Change log
  CHANGELOG.md
  etc/module.xml
Labels: Feature

#1196 Feature/update db scheme 4.0.0
  .circleci/config.yml
  .php-cs-fixer.php
  Api/Data/JobInterface.php
  Api/Data/LandingPageInterface.php
  Api/Data/QueryInterface.php
  Api/Data/RunInterface.php
  Block/Adminhtml/Queue/Status.php
  Block/Navigation/Renderer/DefaultRenderer.php
  CHANGELOG.md
  Controller/Adminhtml/Reindex/Save.php
  Helper/AdapterHelper.php
  Helper/AlgoliaHelper.php
  Helper/AnalyticsHelper.php
  Helper/ConfigHelper.php
  Helper/Configuration/NoticeHelper.php
  Helper/Configuration/PersonalizationHelper.php
  Helper/Entity/PageHelper.php
  Helper/Entity/Product/PriceManager/ProductWithoutChildren.php
  Helper/InsightsHelper.php
  Model/ExtensionNotification.php
  Model/Indexer/AdditionalSection.php
  Model/Indexer/Category.php
  Model/Indexer/Page.php
  Model/Indexer/Product.php
  Model/Indexer/QueueRunner.php
  Model/Indexer/Suggestion.php
  Model/LandingPage.php
  Model/LandingPageUrlRewriteGenerator.php
  Model/Query.php
  Model/Queue.php
  Model/Run.php
  Plugin/RenderingCacheContextPlugin.php
  README.md
  Setup/.DS_Store
  Setup/Patch/Schema/ConfigPatch.php
  Setup/UpgradeData.php
  Setup/UpgradeSchema.php
  Test/Integration/ProductsIndexingTest.php
  Test/Integration/QueueTest.php
  Test/Integration/TestCase.php
  Ui/Component/Listing/Column/LandingPageActions.php
  Ui/Component/Listing/Column/QueryActions.php
  Ui/Component/Listing/Column/QueueActions.php
  ViewModel/Adminhtml/Analytics/Overview.php
  etc/db_schema.xml
  etc/db_schema_whitelist.json
  etc/module.xml
  view/adminhtml/ui_component/algolia_algoliasearch_landingpage_form.xml
  view/adminhtml/ui_component/algolia_algoliasearch_query_form.xml
  view/adminhtml/ui_component/category_form.xml
Labels: enhancement

#1198 Updated release version
  CHANGELOG.md
  README.md
  composer.json
  etc/module.xml
Labels: enhancement
