Repository algolia/algoliasearch-magento-2, pull requests merged in 2024-01, with the labels that each got.

#1417 MAGE-760 Fixed Tier price issue
  Helper/Entity/Product/PriceManager/ProductWithoutChildren.php
Labels: Bug

#1448 Cart recommendations issue for grouped products in add to cart
  ViewModel/Recommend/Cart.php
Labels: Bug

#1463 Created a way for customers to change timeout values for Algolia PHP Client
  Helper/AlgoliaHelper.php
  Helper/ConfigHelper.php
  etc/adminhtml/system.xml
  etc/config.xml
Labels: Feature

#1461 Add German translations
  i18n/de_DE.csv
Labels: Feature

#1446 Bugfix/mage 793 IS filter quoted categories
  view/frontend/web/instantsearch.js
Labels: Bug

#1439 Insights API Update
  Observer/Insights/CustomerLogout.php
  view/frontend/web/insights.js
  view/frontend/web/internals/search-insights.js
Labels: Feature

#1459 MAGE-804 Added configuration for analytics region
  Helper/AnalyticsHelper.php
  Helper/ConfigHelper.php
  Model/Source/AnalyticsRegion.php
  etc/adminhtml/system.xml
  etc/config.xml
Labels: Feature

#1464 Upgrade InstantSearch version in the bundle
  CHANGELOG.md
  README.md
  composer.json
  etc/module.xml
  view/frontend/web/instantsearch.js
  view/frontend/web/internals/algoliaBundle.min.js
Labels: enhancement

#1453 Duplicate Replica Issue one set is standard and another is virtual
  Helper/Entity/ProductHelper.php
  Model/Backend/Sorts.php
Labels: Bug

#1430 MAGE-758 Special price range for configurable products
  Helper/Entity/Product/PriceManager/Configurable.php
  Helper/Entity/Product/PriceManager/ProductWithChildren.php
  Helper/Entity/Product/PriceManager/ProductWithoutChildren.php
Labels: Bug
